# Directori on es guardaran tots els fitxers
# Exemple de Windows ->   D:/projects/rfhab/rfhabfiles
es.caib.rfhab.filesdirectory=/appsfiles/rfhab/files

#  Tipus de FileSystemManager
es.caib.rfhab.filesystemmanagerclass=org.fundaciobit.genapp.common.filesystem.SimpleFileSystemManager
#  Si volem distribuir els fitxers en directoris, llavors utilitzar aquesta classe.
#es.caib.rfhab.filesystemmanagerclass=org.fundaciobit.genapp.common.filesystem.ThreeFolderFileSystemManager




#  ======== PLUGIN USER-INFORMATION - KEYCLOAK =======

es.caib.rfhab.userinformationplugin=org.fundaciobit.pluginsib.userinformation.keycloak.KeyCloakUserInformationPlugin
es.caib.rfhab.pluginsib.userinformation.keycloak.serverurl=http://localhost:18080/auth/
es.caib.rfhab.pluginsib.userinformation.keycloak.realm=GOIB
es.caib.rfhab.pluginsib.userinformation.keycloak.client_id=goib-ws
es.caib.rfhab.pluginsib.userinformation.keycloak.password_secret=secret
es.caib.rfhab.pluginsib.userinformation.keycloak.client_id_for_user_autentication=client

# Mappings. Mapejos entre valors de Attibutes de un usuari i els valors de UserInfo de PluginUserInformation
# Clau:  username, administrationID, name, surname1, surname2, email, language,
#        phoneNumber, password,  address, company, website o gender( -1: unknown or undefined, 0 female, 1 male)
# Valor:  Atribut definit dins "Attributes" de l'usuari Keycloak
es.caib.rfhab.pluginsib.userinformation.keycloak.mapping.administrationID=nif

#es.caib.rfhab.pluginsib.userinformation.keycloak.mapping.company=departmentNumber
#es.caib.rfhab.pluginsib.userinformation.keycloak.mapping.surname1=sn1
#es.caib.rfhab.pluginsib.userinformation.keycloak.mapping.surname2=sn2
# Per depuració
es.caib.rfhab.pluginsib.userinformation.keycloak.debug=true


#  ======== PLUGIN USER-INFORMATION - EXTERNAL DATABASE ======= -->
#es.caib.rfhab.userinformationplugin=org.fundaciobit.pluginsib.userinformation.database.DataBaseUserInformationPlugin
es.caib.rfhab.pluginsib.userinformation.database.jndi=java:jboss/datasources/seyconDS
es.caib.rfhab.pluginsib.userinformation.database.users_table=SC_WL_USUARI
es.caib.rfhab.pluginsib.userinformation.database.username_column=USU_CODI
es.caib.rfhab.pluginsib.userinformation.database.administrationid_column=USU_NIF
es.caib.rfhab.pluginsib.userinformation.database.name_column=USU_NOM
#es.caib.rfhab.pluginsib.userinformation.database.surname_1_column
#es.caib.rfhab.pluginsib.userinformation.database.surname_2_column      
#es.caib.rfhab.pluginsib.userinformation.database.language_column
#es.caib.rfhab.pluginsib.userinformation.database.telephone_column
#es.caib.rfhab.pluginsib.userinformation.database.email_column=CONCAT(USU_CODI,'@fundaciobit.org')
#es.caib.rfhab.pluginsib.userinformation.database.gender_column
#es.caib.rfhab.pluginsib.userinformation.database.password_column
es.caib.rfhab.pluginsib.userinformation.database.userroles_table=SC_WL_USUGRU
es.caib.rfhab.pluginsib.userinformation.database.userroles_rolename_column=UGR_CODGRU
es.caib.rfhab.pluginsib.userinformation.database.userroles_username_column=UGR_CODUSU


#  ======== PLUGIN USER-INFORMATION - LDAP ======= 

# es.caib.rfhab.userinformationplugin=org.fundaciobit.pluginsib.userinformation.ldap.LdapUserInformationPlugin
# es.caib.rfhab.pluginsib.userinformation.ldap.host_url=ldap://ldap.ibit.org:389
# es.caib.rfhab.pluginsib.userinformation.ldap.security_principal=[LDAPUSERNAME]
# es.caib.rfhab.pluginsib.userinformation.ldap.security_authentication=simple
# es.caib.rfhab.pluginsib.userinformation.ldap.security_credentials=[PASSWORD of LDAPUSERNAME]
# es.caib.rfhab.pluginsib.userinformation.ldap.users_context_dn=cn=Users,dc=ibitnet,dc=lan
# es.caib.rfhab.pluginsib.userinformation.ldap.search_scope=onelevel
# es.caib.rfhab.pluginsib.userinformation.ldap.search_filter=(|(memberOf=CN=@PFI_ADMIN,CN=Users,DC=ibitnet,DC=lan)(memberOf=CN=@PFI_USER,CN=Users,DC=ibitnet,DC=lan))
# es.caib.rfhab.pluginsib.userinformation.ldap.attribute.username=sAMAccountName
# es.caib.rfhab.pluginsib.userinformation.ldap.attribute.mail=mail
# es.caib.rfhab.pluginsib.userinformation.ldap.attribute.administration_id=postOfficeBox
# es.caib.rfhab.pluginsib.userinformation.ldap.attribute.name=givenName
# Has de triar:
#       - "surname1" i "surname2"
#       - "surname"
# es.caib.rfhab.pluginsib.userinformation.ldap.attribute.surname=sn

# es.caib.rfhab.pluginsib.userinformation.ldap.attribute.surname1=sn1
# es.caib.rfhab.pluginsib.userinformation.ldap.attribute.surname2=sn2

# es.caib.rfhab.pluginsib.userinformation.ldap.attribute.telephone=telephoneNumber
# es.caib.rfhab.pluginsib.userinformation.ldap.attribute.memberof=memberOf
# es.caib.rfhab.pluginsib.userinformation.ldap.prefix_role_match_memberof=CN=@
# es.caib.rfhab.pluginsib.userinformation.ldap.suffix_role_match_memberof=,CN=Users,DC=ibitnet,DC=lan

# Dades client connexió amb Rolsac
es.caib.rfhab.rolsac.endpoint=endpoint
es.caib.rfhab.rolsac.usuari=usuari
es.caib.rfhab.rolsac.contrasenya=clau
#es.caib.rfhab.rolsac.catxe.ttl està en ms --> 1000L * 60 * 60 * 24 = 24h
es.caib.rfhab.rolsac.catxe.ttl=86400000

# Dades client connexió amb dir3caib
es.caib.rfhab.dir3caib.endpoint=endpoint
es.caib.rfhab.dir3caib.usuari=usuari
es.caib.rfhab.dir3caib.contrasenya=clau

# Dades client connexió amb arxiu
es.caib.rfhab.pluginsib.arxiu.endpoint=endpoint
es.caib.rfhab.pluginsib.arxiu.usuari=usuari
es.caib.rfhab.pluginsib.arxiu.contrasenya=clau
es.caib.rfhab.pluginsib.arxiu.aplicacio=RFHAB
es.caib.rfhab.pluginsib.arxiu.classificacio=organclassificacio
es.caib.rfhab.pluginsib.arxiu.serieDocumental=SXXXY
es.caib.rfhab.pluginsib.arxiu.conversio.imprimible.url=endpoint
es.caib.rfhab.pluginsib.arxiu.conversio.imprimible.usuari=usuari
es.caib.rfhab.pluginsib.arxiu.conversio.imprimible.contrasenya=clau

# Dades client connexió amb scanweb
es.caib.rfhab.pluginsib.scanweb.endpoint=endpoint
es.caib.rfhab.pluginsib.scanweb.usuari=usuari
es.caib.rfhab.pluginsib.scanweb.contrasenya=clau
es.caib.rfhab.pluginsib.scanweb.profile=perfil

# Dades client connexió amb sistramit
sistramit.url=endpoint
sistramit.usuari=usuari
sistramit.contrasenya=clau