/*
 * API REST INTERNA de RFHab
 * Serveis REST de RFHab per ser accedits emprant autenticació
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.rfhab.api.interna.client.rfhab.v1.api;

import es.caib.rfhab.api.interna.client.rfhab.v1.services.ApiClient;
import es.caib.rfhab.api.interna.client.rfhab.v1.services.ApiException;
import es.caib.rfhab.api.interna.client.rfhab.v1.services.auth.HttpBasicAuth;
import es.caib.rfhab.api.interna.client.rfhab.v1.model.FitxersCarrega;
import es.caib.rfhab.api.interna.client.rfhab.v1.model.RestExceptionInfo;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;

/**
 * API tests for CarregaDadesServiceApi
 */
class CarregaDadesServiceApiTest {
    
    public static void main(String[] args) {
        CarregaDadesServiceApiTest test = new CarregaDadesServiceApiTest();
        try {
            test.carregaInicialDadesTest();
        } catch (ApiException e) {
            System.err.println("Exception when calling CarregaDadesServiceApi#carregaInicialDadesTest");
            e.printStackTrace();
        }
    }

    /**
     * Carrega inicial de dades
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void carregaInicialDadesTest() throws ApiException {
        
        
        //
        //FitxersCarrega usuari = null;
        //
        //String response = api.carregaInicialDades(usuari);
        try {
            
        ApiClient client = new ApiClient();
        // client.setBasePath("https://governdigital.fundaciobit.org/rfhabapi/interna");
        client.setBasePath("http://localhost:8080/rfhabapi/interna");
        HttpBasicAuth auth = (HttpBasicAuth) client.getAuthentication("BasicAuth");
        Properties properties = new Properties();
        try (InputStream inputStream = Files.newInputStream(new File("carregadormassiu.properties").toPath())) {
            properties.load(inputStream);
        }
        String username = properties.getProperty("usuari", properties.getProperty("carregadormassiu.usuari"));
        String password = properties.getProperty("contrasenya", properties.getProperty("carregadormassiu.contrasenya"));
        if (username == null || password == null) {
            throw new IllegalStateException("No s'han trobat les propietats 'usuari' i 'contrasenya' a carregadormassiu.properties");
        }
        auth.setUsername(username);
        auth.setPassword(password);
        final CarregaDadesServiceApi api = new CarregaDadesServiceApi(client);


        FitxersCarrega fitxers = new FitxersCarrega();
        fitxers.setExcel(Files.readAllBytes(new File("20260610 RFH COMPLET.ods").toPath()));
        fitxers.setProperties(Files.readAllBytes(new File("carregadormassiu.properties").toPath()));

        String response = api.carregaInicialDades(fitxers);
        System.out.println("Response: " + response);
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
