/*
 * API REST INTERNA de RFHab
 * Serveis REST de RFHab per ser accedits emprant autenticació
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.rfhab.api.interna.client.rfhab.v1.api;

import es.caib.rfhab.api.interna.client.rfhab.v1.services.ApiException;
import es.caib.rfhab.api.interna.client.rfhab.v1.model.RestExceptionInfo;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FuncionariRestServiceApi
 */
class FuncionariRestServiceApiTest {

    private final FuncionariRestServiceApi api = new FuncionariRestServiceApi();

    /**
     * Comprobar si un funcionari té permís per realitzar un trámit
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void comprobarAutoritzaciTest() throws ApiException {
        //
        //List<String> usuari = null;
        //
        //List<String> codisia = null;
        //
        //List<String> entitat = null;
        //
        //String language = null;
        //
        //String response = api.comprobarAutoritzaci(usuari, codisia, entitat, language);

        // TODO: test validations
    }
    /**
     * Consulta les habilitacions d&#39;un funcionari habilitat
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void habilitacionsTest() throws ApiException {
        //
        //List<String> usuari = null;
        //
        //List<String> entitat = null;
        //
        //String response = api.habilitacions(usuari, entitat);

        // TODO: test validations
    }
    /**
     * Obtenir les habilitacions associades a un/a funcionari/ària
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void obtenirHabilitacionsFuncionariTest() throws ApiException {
        //
        //List<String> usuari = null;
        //
        //List<String> habilitacio = null;
        //
        //List<String> entitat = null;
        //
        //String response = api.obtenirHabilitacionsFuncionari(usuari, habilitacio, entitat);

        // TODO: test validations
    }
}
