/*
 * API REST INTERNA de RFHab
 * Serveis REST de RFHab per ser accedits emprant autenticació
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.rfhab.api.interna.client.rfhab.v1.api;

import es.caib.rfhab.api.interna.client.rfhab.v1.services.ApiException;
import es.caib.rfhab.api.interna.client.rfhab.v1.model.RestExceptionInfo;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RegistreActivitatFuncionariServiceApi
 */
class RegistreActivitatFuncionariServiceApiTest {

    private final RegistreActivitatFuncionariServiceApi api = new RegistreActivitatFuncionariServiceApi();

    /**
     * Registra una activiat d&#39;un funcionari
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void registreActivitatTest() throws ApiException {
        //
        //String funcionari = null;
        //
        //String tipus = null;
        //
        //String data = null;
        //
        //String language = null;
        //
        //String identificadorcopiaautentica = null;
        //
        //String registre = null;
        //
        //String idactuaciotramitfh = null;
        //
        //String response = api.registreActivitat(funcionari, tipus, data, language, identificadorcopiaautentica, registre, idactuaciotramitfh);

        // TODO: test validations
    }
}
