carregadormassiu.url=http://localhost:8080/rfhabapi/interna
carregadormassiu.usuari=rfhab
carregadormassiu.contrasenya=rfhab
carregadormassiu.usuaricarregadorid=1
carregadormassiu.entitatcarregadorid=1
