# Exemple de mapping columna ODS -> propietat DTO
NÚM.\ RFH=numRfh
1r\ LLINATGE=primerLlinatge
2n\ LLINATGE=segonLlinatge
NOM=nom
NIF=nif
Usuari=usuari
Adreça\ electrònica=adrecaElectronica
DIR3\ (NORMALITZAT)=dir3UnitatSuperiorNormalitzat
DIR3=dir3UnitatSuperior
Nom\ conselleria=nomUnitatSuperior
DIR3\ unitat\ orgànica\ (NORMALITZAT)=dir3UnitatOrganicaNormalitzat
DIR3\ unitat\ orgànica=dir3UnitatOrganica
Nom\ unitat\ orgànica=nomUnitatOrganica
Codi\ lloc\ de\ feina=codiLlocFeina
Expansió=expansio
Nom\ lloc\ de\ feina=nomLlocFeina
Nom\ màquina=nomMaquina
OAMR=oamr
Habilitació=habilitacio
Núm.\ C\ AI\ Assignació=numCaiAlta
Data\ d\'assignació=dataAlta
Observacions\ alta=observacionsAlta
Data\ de\ desassignació=dataDesassignacio
Data\ BAIXA=dataBaixa
Observacions\ baixa=observacionsBaixa
