-- create index rfh_activitat_pk_i on rfh_activitat (activitatid);
create index rfh_activitat_autoritzaid_fk_i on rfh_activitat (autoritzacioid);
create index rfh_autoritza_funid_fk_i on rfh_autoritzacio (llocid);
-- create index rfh_digitalib_pk_i on rfh_digitalib (digitalid);
create index rfh_digitalib_usuariid_fk_i on rfh_digitalib (usuariid);
create index rfh_entitat_unitatid_fk_i on rfh_entitat (unitatid);
-- create index rfh_funcionari_pk_i on rfh_funcionari (funcionariid);
create index rfh_funcionarilloc_llocid_fk_i on rfh_funcionarilloc (llocid);
create index rfh_funrol_funcionariid_fk_i on rfh_funcionarirol (funcionariid);
-- create index rfh_historic_pk_i on rfh_historic (historicid);
create index rfh_historic_usuariid_fk_i on rfh_historic (usuariid);
create index rfh_historiclloc_llocid_fk_i on rfh_historiclloc (llocid);
-- create index rfh_idioma_pk_i on rfh_idioma (idiomaid);
create index rfh_lloc_entitatid_fk_i on rfh_lloc (entitatid);
create index rfh_plugin_entitatid_fk_i on rfh_plugin (entitatid);
create index rfh_rol_nomid_fk_i on rfh_rol (nomid);
-- create index rfh_unitat_pk_i on rfh_unitat (unitatid);
create index rfh_usuari_idiomaid_fk_i on rfh_usuari (idiomaid);
create index rfh_usuarient_entitatid_fk_i on rfh_usuarientitat (entitatid);
