/* Generated by Together */

package es.caib.rfhab.pluginsib.rolsac.model.ibitrolsac;



public class ElementTramit extends Ordenable  {
    private Tramite tramite;

    
	public Tramite getTramite() {
		return tramite;
	}
	
	public void setTramite(Tramite tramite) {
		this.tramite = tramite;
	}



	@Override
	public String toString() {
		long tid=tramite==null?-1:tramite.getId();
		return "DocumentTramit [tramite=" + tid + super.toString()+"]";
	}

}
