/* Generated by Together */

package es.caib.rfhab.pluginsib.rolsac.model.ibitrolsac;


public class HistoricoNormativa extends Historico {

    public Normativa getNormativa() {
        return normativa;
    }

    public void setNormativa(Normativa normativa) {
        this.normativa = normativa;
    }

    private Normativa normativa;
}
