/* Generated by Together */

package es.caib.rfhab.pluginsib.rolsac.model.ibitrolsac;



public class RequisitTramit extends ElementTramit  {

	@Override
	public String toString() {

		return "RequisitTramit [" +super.toString()+"]";
	}

}
