/* Generated by Together */

package es.caib.rfhab.pluginsib.rolsac.model.ibitrolsac;

public interface Traduccion extends ValueObject {
	// public List<Map<String, Object>> translate(final Traduccion traduccionOrigen,
	// final String langDefault, final boolean textoPanto);
}
