/* Generated by Together */

package es.caib.rfhab.pluginsib.rolsac.model.ibitrolsac;

/**
 *
 */
public class TraduccionDocumento implements Traduccion {

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Archivo getArchivo() {
        return archivo;
    }

    public void setArchivo(Archivo archivo) {
        this.archivo = archivo;
    }

    private String titulo;
    private String descripcion;
    private Archivo archivo;
}
