/* Generated by Together */

package es.caib.rfhab.pluginsib.rolsac.model.ibitrolsac;


public class TraduccionEdificio implements Traduccion {

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    private String descripcion;
}
