/* Generated by Together */

package es.caib.rfhab.pluginsib.rolsac.model.ibitrolsac;

/**
 * Traduccion de normativa remota.
 * @author slromero
 *
 */
public class TraduccionNormativaRemota extends TraduccionNormativa {

    /** Serial Version UID. **/
	private static final long serialVersionUID = 1L;

	/**
	 * Get Responsable. 
	 * @return
	 */
	public String getResponsable() {
        return responsable;
    }

	/** 
	 * Set responsable. 
	 * @param responsable
	 */
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }

    /** Responsable. **/
    private String responsable;
}
