<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>rfhab-commons</artifactId>
	<packaging>jar</packaging>

	<parent>
		<groupId>es.caib.rfhab</groupId>
		<artifactId>rfhab</artifactId>
		<version>1.0.0</version>
	</parent>

	<name>RFHab - Commons</name>

	<properties>
        <project.buildtime>${maven.build.timestamp}</project.buildtime>
		<xdocreport.version>2.0.4</xdocreport.version>
		<maven.test.skip>false</maven.test.skip>
	</properties>


	<build>
		<finalName>${project.artifactId}-${project.version}</finalName>
		<resources>
			<!-- Activam filtre per fer substitucions al fitxer Version.properties -->
			<resource>
				<directory>${project.basedir}/src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>

		<plugins>

			<!-- Defineix la propietat {buildNumber} que s'empra al filtrat -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
			</plugin>

		</plugins>

	</build>

	<dependencies>
		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-api</artifactId>
			<scope>provided</scope>
		</dependency>
		
		<!-- OPENSAGRES XDOCREPORT (to merge odt,docx with Java model and convert to PDF) -->
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.odfdom.converter.core</artifactId>
			<version>${xdocreport.version}</version>
			<!-- <exclusions>
					<exclusion>
						<groupId>xerces</groupId>
						<artifactId>xercesImpl</artifactId>
					</exclusion>
			</exclusions> -->
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.converter.odt.odfdom</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.document.odt</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.template.freemarker</artifactId>
			<version>${xdocreport.version}</version>
			<exclusions>
				<!-- This avoids ParseException in template due to unknown built-in: "counter" in freemarker 2.3.20 -->
				<exclusion>
					<groupId>org.freemarker</groupId>
					<artifactId>freemarker</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.template.velocity</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>
		<!-- This avoids ParseException in template due to unknown built-in: "counter" in freemarker 2.3.20 -->
		<dependency>
			<groupId>org.freemarker</groupId>
			<artifactId>freemarker</artifactId>
			<version>2.3.32</version>
		</dependency>

		<dependency>
            <groupId>com.fasterxml.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-json-provider</artifactId>
            <scope>provided</scope>
        </dependency>

		<!-- Anotacions de documentació de openapi -->
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <scope>provided</scope>
        </dependency>

	</dependencies>

</project>
