<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>rfhab</artifactId>
        <groupId>es.caib.rfhab</groupId>
        <version>1.0.3</version>
    </parent>
    <artifactId>rfhab-api-interna</artifactId>
    <packaging>war</packaging>
    <name>RFHab - API Rest - Interna Server</name>
    <properties>
        <auth.method>BASIC</auth.method>
        <client.default.package>es.caib.rfhab.api.interna.client</client.default.package>
    </properties>

    <dependencies>
        <!-- Altres mòduls del projecte -->
        <dependency>
            <groupId>es.caib.rfhab</groupId>
            <artifactId>rfhab-commons</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>es.caib.rfhab</groupId>
            <artifactId>rfhab-persistence</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>es.caib.rfhab</groupId>
            <artifactId>rfhab-model</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>es.caib.rfhab</groupId>
            <artifactId>rfhab-ejb</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>es.caib.rfhab</groupId>
            <artifactId>rfhab-rolsac-model</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        
		<!-- Externas -->
		
        <dependency>
			<groupId>org.fundaciobit.genapp</groupId>
			<artifactId>genapp-core</artifactId>
			<version>${genapp.version}</version>
			<scope>provided</scope>
		</dependency>

        <!-- Anotacions de documentació de openapi -->
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <artifactId>pluginsib-utils-rest</artifactId>
            <groupId>org.fundaciobit.pluginsib.utils</groupId>
            <version>${pluginsib.utils.rest.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.utils</groupId>
            <artifactId>pluginsib-utils-swagger-ui-configurable-webjar</artifactId>
            <version>${pluginsib.utils.version}</version>
        </dependency>

        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <scope>provided</scope>
        </dependency>

    </dependencies>
    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-resources</id>
						<phase>validate</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/classes</outputDirectory>
							<resources>
								<resource>
									<directory>${basedir}/../rfhab-ejb/src/main/resources</directory>
									<includes>
										<include>logicmissatges_*.properties</include>
										<include>genapp_*.properties</include>
										<include>rfhab_genapp_*.properties</include>
									</includes>
									<filtering>true</filtering>
								</resource>
							</resources>
							<overwrite>true</overwrite>
						</configuration>
					</execution>
				</executions>
			</plugin>

            <!-- comprovació d'apòstrof dins els fitxers properties -->
            <!-- El problema és que la tasca Ant <resourcecontains> cerca fitxers en el directori de treball actual, però per defecte només cerca dins l’arxiu JAR/target, no a src/main/resources ni als fitxers copiats per Maven. Això fa que no trobi el fitxer nom_fitxer.properties amb l’apòstrof -->
            <!-- Durant la fase validate, Maven encara no ha copiat els fitxers de src/main/resources a target/classes. Per això la tasca Ant <resourcecontains> només pot trobar fitxers que ja existeixen al sistema de fitxers en aquell moment (normalment a src/main/resources, no a target/classes) -->
            <!-- <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <fail message="S'ha trobat un apòstrof (') en algun fitxer .properties!">
                                    <condition>
                                        <resourcecontains resource="**/*.properties" substring="'"/>
                                    </condition>
                                </fail>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin> -->
            
            <!-- Genera el descriptor openapi.json de forma estàtica, després 
                el posarem l'arrel del WAR -->
            <!-- https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-maven-plugin -->
            <plugin>

                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <version>2.2.15</version>
                
                <configuration>
                    <outputFormat>JSON</outputFormat>
                    <prettyPrint>TRUE</prettyPrint>
                    <outputPath>${project.basedir}/openapi/</outputPath>                   
                </configuration>

                <executions>
                    <execution>
                        <id>openapi_interna_1</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>resolve</goal>
                        </goals>
                        <configuration>
                            <contextId>RFHab API Interna Public</contextId>
                            <outputFileName>rfhab_api_interna_public</outputFileName>
                            <resourcePackages>
                                <package>es.caib.rfhab.api.interna.config</package>
                                <package>es.caib.rfhab.api.interna.all.general</package>
                                <package>es.caib.rfhab.api.interna.all.habilitacio</package>
                            </resourcePackages>
                        </configuration>
                    </execution>
                    <execution>
                        <id>openapi_interna_2</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>resolve</goal>
                        </goals>
                        <configuration>
                            <contextId>RFHab API Interna Seguretat</contextId>
                            <outputFileName>rfhab_api_interna_secure</outputFileName>
                            <resourcePackages>
                                <package>es.caib.rfhab.api.interna.config</package>
                                <package>es.caib.rfhab.api.interna.secure.activitat</package>
                                <package>es.caib.rfhab.api.interna.secure.funcionari</package>
                                <package>es.caib.rfhab.api.interna.secure.lloc</package>
                                <package>es.caib.rfhab.api.interna.secure.funcionarilloc</package>
                                <package>es.caib.rfhab.api.interna.secure.carregadades</package>
                            </resourcePackages>
                        </configuration>
                    </execution>
                    <execution>
                        <id>openapi_interna_3</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>resolve</goal>
                        </goals>
                        <configuration>
                            <contextId>RFHab API Interna Dades Obertes</contextId>
                            <outputFileName>rfhab_api_interna_dadesobertes</outputFileName>
                            <resourcePackages>
                                <package>es.caib.rfhab.api.interna.config</package>
                                <package>es.caib.rfhab.api.interna.all.exemplereutilitzacio</package>
                            </resourcePackages>
                        </configuration>
                    </execution>
                </executions>
            </plugin>


            <!-- ==================================================================  -->
            <!-- Genera el Client Rest per Java a partir del fitxers openapi_*.json -->
            <!-- ==================================================================  -->
            <plugin>
                <!-- https://openapi-generator.tech/docs/generators/java/ -->
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.10.0</version>

                <executions>
                    <!--execution>
                        <id>openapi_interna_1</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/openapi/openapi_interna_public.json</inputSpec>
                            <generatorName>java</generatorName>
                            <skipValidateSpec>true</skipValidateSpec>
                            <configHelp>java</configHelp>
                            <library>resteasy</library>
                            <addCompileSourceRoot>false</addCompileSourceRoot>
                            <output>${project.basedir}/../rfhab-api-interna-client-exemplepublic-v1</output>
                            <apiPackage>${client.default.package}.exemplepublic.v1.api</apiPackage>
                            <modelPackage>${client.default.package}.exemplepublic.v1.model</modelPackage>
                            <invokerPackage>${client.default.package}.exemplepublic.v1.services</invokerPackage>
                            <generateModelTests>false</generateModelTests>
                            <configOptions>
                                <groupId>es.caib.rfhab</groupId>
                                <artifactId>rfhab-api-interna-client-exemplepublic-v1</artifactId>
                                <artifactVersion>1.0-SNAPSHOT</artifactVersion>
                                <artifactDescription>RFHab - API Rest -  Interna Client - Exemple Public v1</artifactDescription>
                                <dateLibrary>java8</dateLibrary>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <java11>true</java11>
                            </configOptions>
                        </configuration>
                    </execution> -->
                    <execution>
                        <id>openapi_interna_2</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>
                                ${project.basedir}/openapi/rfhab_api_interna_secure.json</inputSpec>
                            <generatorName>java</generatorName>
                            <skipValidateSpec>true</skipValidateSpec>
                            <configHelp>java</configHelp>
                            <library>resteasy</library>
                            <addCompileSourceRoot>false</addCompileSourceRoot>
                            <output>${project.basedir}/../rfhab-api-interna-client-v1</output>
                            <apiPackage>${client.default.package}.rfhab.v1.api</apiPackage>
                            <modelPackage>${client.default.package}.rfhab.v1.model</modelPackage>
                            <invokerPackage>${client.default.package}.rfhab.v1.services</invokerPackage>
                            <generateModelTests>false</generateModelTests>
                            <configOptions>
                                <groupId>es.caib.rfhab</groupId>
                                <artifactId>rfhab-api-interna-client-rfhab-v1</artifactId>
                                <artifactVersion>1.0-SNAPSHOT</artifactVersion>
                                <artifactDescription>RFHab - API Rest - Interna Client - RFHAB v1</artifactDescription>
                                <dateLibrary>java8</dateLibrary>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <java11>true</java11>
                            </configOptions>
                        </configuration>
                    </execution> 
                    <!-- openapi3:  Dades Obertes no necessita Client JAVA -->
                    <!-- openapi3:  Rolsac -->
                    <!-- execution
                        <id>openapi_rolsac</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>
                                ${project.basedir}/openapi/swagger_rolsac.json</inputSpec>
                            <generatorName>java</generatorName>
                            <skipValidateSpec>true</skipValidateSpec>
                            <configHelp>java</configHelp>
                            <library>resteasy</library>
                            <addCompileSourceRoot>false</addCompileSourceRoot>
                            <output>${project.basedir}/../rfhab-api-rolsac-client</output>
                            <apiPackage>es.caib.rfhab.pluginsib.rolsac.client.v1.api</apiPackage>
                            <modelPackage>es.caib.rfhab.pluginsib.rolsac.client.v1.model</modelPackage>
                            <invokerPackage>es.caib.rfhab.pluginsib.rolsac.client.v1.services</invokerPackage>
                            <generateModelTests>false</generateModelTests>
                            <configOptions>
                                <groupId>es.caib.rfhab</groupId>
                                <artifactId>rfhab-api-interna-rolsac-client</artifactId>
                                <artifactVersion>1.0-SNAPSHOT</artifactVersion>
                                <artifactDescription>RFHab - API Rest - Rolsac Client</artifactDescription>
                                <dateLibrary>java8</dateLibrary>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <java11>true</java11>
                            </configOptions>
                        </configuration>
                    execution -->
                    
                    <!-- openapi3:  Dir3Caib -->
                    <!-- execution>
                        <id>openapi_dir3caib</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>
                                ${project.basedir}/openapi/swagger_dir3caib_se.json</inputSpec>
                            <generatorName>java</generatorName>
                            <skipValidateSpec>true</skipValidateSpec>
                            <configHelp>java</configHelp>
                            <library>resteasy</library>
                            <addCompileSourceRoot>false</addCompileSourceRoot>
                            <output>${project.basedir}/../rfhab-pluginsib-dir3caib-client</output>
                            <apiPackage>es.caib.rfhab.pluginsib.dir3caib.client.v1.api</apiPackage>
                            <modelPackage>es.caib.rfhab.pluginsib.dir3caib.client.v1.model</modelPackage>
                            <invokerPackage>es.caib.rfhab.pluginsib.dir3caib.client.v1.services</invokerPackage>
                            <generateModelTests>false</generateModelTests>
                            <configOptions>
                                <groupId>es.caib.rfhab</groupId>
                                <artifactId>rfhab-pluginsib-dir3caib-client</artifactId>
                                <artifactVersion>1.0-SNAPSHOT</artifactVersion>
                                <artifactDescription>RFHab - API Rest - Rolsac Client</artifactDescription>
                                <dateLibrary>java8</dateLibrary>
                                <useTags>true</useTags>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <java11>true</java11>
                            </configOptions>
                        </configuration>
                    </execution -->
                                       
                </executions>
            </plugin>

            <!--NOU TODO -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <includeProjectDependencies>false</includeProjectDependencies>
                    <includePluginDependencies>true</includePluginDependencies>
                    <executableDependency>
                        <artifactId>pluginsib-utils-rest</artifactId>
                        <groupId>org.fundaciobit.pluginsib.utils</groupId>
                    </executableDependency>
                    <mainClass>
                        org.fundaciobit.pluginsib.utils.rest.pomadaptertojboss72.AdaptApiClientPomToJboss72</mainClass>
                    <arguments>
                        <argument>${project.basedir}</argument>
                    </arguments>
                </configuration>
                <dependencies>
                    <dependency>
                        <artifactId>pluginsib-utils-rest</artifactId>
                        <groupId>org.fundaciobit.pluginsib.utils</groupId>
                        <version>${pluginsib.utils.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

            <!-- Inclou el openapi.json i el swagger-ui dins el war -->
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <packagingExcludes>
                        **/jackson-datatype-jsr310*redhat*.jar,
                        **/json-patch*redhat*.jar,
                        **/jboss-jaxrs-api_2.1_spec*redhat*.jar,
                        **/resteasy-jackson2-provider*redhat*.jar
                    </packagingExcludes>
                    <filteringDeploymentDescriptors>true</filteringDeploymentDescriptors>
                    <webResources>
                        <resource>
                            <directory>${project.basedir}/openapi</directory>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>

        </plugins>

    </build>

</project>