<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>rfhab-ejb</artifactId>
    <packaging>ejb</packaging>

    <parent>
        <groupId>es.caib.rfhab</groupId>
        <artifactId>rfhab</artifactId>
        <version>1.0.4</version>
    </parent>

    <name>RFHab - EJB</name>

    <properties>
            <maven.test.skip>false</maven.test.skip>
    </properties>

    <dependencies>

        <dependency>
            <groupId>es.caib.rfhab</groupId>
            <artifactId>rfhab-model</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>es.caib.rfhab</groupId>
            <artifactId>rfhab-persistence</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>es.caib.rfhab</groupId>
            <artifactId>rfhab-commons</artifactId>
            <version>${project.version}</version>
        </dependency>        
        
        <dependency>
            <groupId>es.caib.rfhab.pluginsib</groupId>
            <artifactId>rfhab-pluginsib-arxiu</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
			<groupId>es.caib.rfhab.pluginsib</groupId>
			<artifactId>rfhab-pluginsib-digitalib</artifactId>
			<version>${project.version}</version>
        </dependency>

		<dependency>
			<groupId>es.caib.rfhab</groupId>
			<artifactId>rfhab-rolsac-model</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>com.github.ben-manes.caffeine</groupId>
			<artifactId>caffeine</artifactId>
			<version>3.1.8</version>
			<exclusions>
				<exclusion>
					<groupId>com.google.errorprone</groupId>
					<artifactId>error_prone_annotations</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <scope>provided</scope>
        </dependency>        
        
         <!-- ===== PLUGINS IB -->
        <dependency>
            <artifactId>pluginsib-userinformation-api</artifactId>
            <groupId>org.fundaciobit.pluginsib.userinformation</groupId>
            <version>${pluginsib.userinformation.version}</version>
        </dependency>
        
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>

        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.dom4j</groupId>
                    <artifactId>dom4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.xml.bind</groupId>
                    <artifactId>jaxb-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        
        <dependency>
            <groupId>org.fundaciobit.pluginsib.utils</groupId>
            <artifactId>pluginsib-utils-templateengine</artifactId>
            <version>${pluginsib.utils.templateengine}</version>
        </dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-json-provider</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>${spring.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-fileupload</groupId>
            <artifactId>commons-fileupload</artifactId>
            <version>1.3</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-io</groupId>
                    <artifactId>commons-io</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.odftoolkit</groupId>
            <artifactId>odfdom-java</artifactId>
        </dependency>

        <!-- Dependències de test -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
		
		<dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.5</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.jboss.slf4j</groupId>
            <artifactId>slf4j-jboss-logmanager</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.dom4j</groupId>
            <artifactId>dom4j</artifactId>
            <version>2.1.4</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <artifactId>pluginsib-utils-rest</artifactId>
            <groupId>org.fundaciobit.pluginsib.utils</groupId>
            <version>${pluginsib.utils.rest.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>

        <finalName>${project.artifactId}-${project.version}</finalName>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ejb-plugin</artifactId>
                <configuration>
                    <ejbVersion>3.2</ejbVersion>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>