<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<artifactId>rfhab-pluginsib</artifactId>
	<groupId>es.caib.rfhab.pluginsib</groupId>
	<packaging>pom</packaging>
	
	<name>RFHab - PluginsIB</name>
	<modules>
		<module>rfhab-pluginsib-rolsac</module>
		<module>rfhab-pluginsib-arxiu</module>
		<module>rfhab-pluginsib-digitalib</module>
		<module>rfhab-pluginsib-dir3caib</module>
	</modules>
	
	<parent>
		<groupId>es.caib.rfhab</groupId>
		<artifactId>rfhab</artifactId>
		<version>1.0.2</version>
	</parent>
</project>