# PLUGIN ARXIU - CAIB

es.caib.rfhab.pluginsib.arxiu.endpoint=https://esbse.caib.es:4430/esb
es.caib.rfhab.pluginsib.arxiu.aplicacio=RFHAB
es.caib.rfhab.pluginsib.arxiu.usuari=usuari
es.caib.rfhab.pluginsib.arxiu.contrasenya=contrasenya
es.caib.rfhab.pluginsib.arxiu.conversio.imprimible.url=url_concsbv
es.caib.rfhab.pluginsib.arxiu.conversio.imprimible.usuari=usuari
es.caib.rfhab.pluginsib.arxiu.conversio.imprimible.contrasenya=contrasenya


#TimeOuts per arxiu:
es.caib.rfhab.pluginsib.arxiu.timeout.connect=10000
es.caib.rfhab.pluginsib.arxiu.timeout.read=60000

es.caib.rfhab.pluginsib.arxiu.documentImprimible.downloadDirectory=ruta/inventada


es.caib.rfhab.pluginsib.arxiu.classificacio=organSiaInvent_RFHAB_123456789
es.caib.rfhab.pluginsib.arxiu.serieDocumental=SXXX1