_projectName_=rfhab
_projectPrefix_=rfh
rfh_activitat=activitat
rfh_activitat_PK=rfh_activitat_pk
rfh_autoritzacio=autoritza
rfh_autoritzacio_PK=rfh_autoritzacio_pk
rfh_entitat=entitat
rfh_entitat_PK=rfh_entitat_pk
rfh_fitxer=fitxer
rfh_fitxer_PK=rfh_fitxer_pk
rfh_funcionari=funcionari
rfh_funcionari_PK=rfh_funcionari_pk
rfh_funcionari_identificador_uk=rfh_funcionari_identific_uk
rfh_funcionarilloc=funlloc
rfh_funcionarilloc_PK=rfh_funcionarilloc_pk
rfh_habilitacio=Habilitaci
rfh_habilitacio_PK=rfh_habilitacio_pk
rfh_historic=historic
rfh_historic_PK=rfh_historic_pk
rfh_historiclloc=histolloc
rfh_historiclloc_PK=rfh_historiclloc_pk
rfh_idioma=idioma
rfh_idioma_PK=rfh_idioma_pk
rfh_lloc=lloc
rfh_lloc_UNIQUE_(expansio,\ codilloc)=rfh_lloc_codillocexpansio_uk
rfh_lloc_PK=rfh_lloc_pk
rfh_lloc_codillocpropi_uk=rfh_lloc_codillocpropi_uk
rfh_llochabilitacio=llochabil
rfh_llochabilitacio_PK=rfh_llochabilitacio_pk
rfh_plugin=plugin
rfh_plugin_PK=rfh_plugin_pk
rfh_digitalib=scanweb
rfh_digitalib_PK=rfh_digitalib_pk
rfh_traduccio=traduccio
rfh_traduccio_PK=rfh_traduccio_pk
rfh_traducciomap=traducmap
rfh_traducciomap_PK=rfh_traducmap_pk
rfh_traducciomap_PK=rfh_traducmap_pk
rfh_unitat=unitat
rfh_unitat_PK=rfh_unitat_pk
rfh_usuari=usuari
rfh_usuari_PK=rfh_usuari_pk
rfh_usuari_username_uk=rfh_usuari_username_uk
rfh_usuarientitat=usuarient
rfh_usuarientitat_UNIQUE_(entitatid,\ usuariid)=rfh_usuarient_multiple_uk
rfh_usuarientitat_PK=rfh_usuarientitat_pk
