/* Generated by Together */

package es.caib.rfhab.pluginsib.rolsac.model.ibitrolsac;


public class HistoricoUA extends Historico {

    public UnidadAdministrativa getUa() {
        return ua;
    }

    public void setUa(UnidadAdministrativa ua) {
        this.ua = ua;
    }

    private UnidadAdministrativa ua;
}
