/* Generated by Together */

package es.caib.rfhab.pluginsib.rolsac.model.ibitrolsac;

@Deprecated
public class TraduccionDocumentTramit extends TraduccionElementOrdenat {

    public Archivo getArchivo() {
        return archivo;
    }

    public void setArchivo(Archivo archivo) {
        this.archivo = archivo;
    }

    private Archivo archivo;
}
