/* Generated by Together */

package es.caib.rfhab.pluginsib.rolsac.model.ibitrolsac;


public class TraduccionTipo implements Traduccion {

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    private String nombre;
}
