/* Generated by Together */

package es.caib.rfhab.pluginsib.rolsac.model.ibitrolsac;


public class TraduccionPerfilCiudadano implements Traduccion {

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    private String nombre;
    private String descripcion;
}
