/* Generated by Together */

package es.caib.rfhab.pluginsib.rolsac.model.ibitrolsac;

import java.io.Serializable;

/**
 * Un ValueObject representa el modelo Java de un formulario struts.
 * @author u92770
 *
 */

public interface ValueObject extends Serializable {

}
