TRUNCATE TABLE RFHAB.RFH_HISTORIC;

DELETE FROM RFHAB.RFH_FUNCIONARI
WHERE funcionariid <> 1;

TRUNCATE TABLE RFHAB.RFH_FUNCIONARILLOC;
TRUNCATE TABLE RFHAB.RFH_HISTORICLLOC;
TRUNCATE TABLE RFHAB.RFH_LLOCHABILITACIO;
TRUNCATE TABLE RFHAB.RFH_TRADUCCIOMAP;
TRUNCATE TABLE RFHAB.RFH_USUARIENTITAT;
TRUNCATE TABLE RFHAB.RFH_ACTIVITAT;
TRUNCATE TABLE RFHAB.RFH_AUTORITZACIO;

DELETE FROM RFHAB.RFH_HABILITACIO;
DELETE FROM RFHAB.RFH_TRADUCCIO;
DELETE FROM RFHAB.RFH_USUARI;
DELETE FROM RFHAB.RFH_IDIOMA;
DELETE FROM RFHAB.RFH_FUNCIONARI;
DELETE FROM RFHAB.RFH_LLOC;
DELETE FROM RFHAB.RFH_ENTITAT;
DELETE FROM RFHAB.RFH_UNITAT;
