/*
 * API REST INTERNA de RFHab
 * Serveis REST de RFHab per ser accedits emprant autenticació
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: governdigital@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.rfhab.api.interna.client.rfhab.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FitxersCarrega
 */
@JsonPropertyOrder({
  FitxersCarrega.JSON_PROPERTY_EXCEL,
  FitxersCarrega.JSON_PROPERTY_PROPERTIES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class FitxersCarrega {
  public static final String JSON_PROPERTY_EXCEL = "excel";
  @javax.annotation.Nullable
  private byte[] excel;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  @javax.annotation.Nullable
  private byte[] properties;

  public FitxersCarrega() {
  }

  public FitxersCarrega excel(@javax.annotation.Nullable byte[] excel) {
    
    this.excel = excel;
    return this;
  }

  /**
   * Excel.
   * @return excel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXCEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getExcel() {
    return excel;
  }


  @JsonProperty(JSON_PROPERTY_EXCEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExcel(@javax.annotation.Nullable byte[] excel) {
    this.excel = excel;
  }

  public FitxersCarrega properties(@javax.annotation.Nullable byte[] properties) {
    
    this.properties = properties;
    return this;
  }

  /**
   * Excel.
   * @return properties
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getProperties() {
    return properties;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProperties(@javax.annotation.Nullable byte[] properties) {
    this.properties = properties;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FitxersCarrega fitxersCarrega = (FitxersCarrega) o;
    return Arrays.equals(this.excel, fitxersCarrega.excel) &&
        Arrays.equals(this.properties, fitxersCarrega.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Arrays.hashCode(excel), Arrays.hashCode(properties));
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FitxersCarrega {\n");
    sb.append("    excel: ").append(toIndentedString(excel)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

